### ISSUE TITLE
Duo login broken

### ISSUE THREAD

**Issue by mahfoozm** [Juan-Olivos/enroll-forku#1]
Duo requires a code to be entered on the mobile app when authenticating. Possible solution is to look for `#auth-view-wrapper > div:nth-child(2) > div.row.display-flex.align-flex-justify-content-center.verification-code"` in modules/login and display the verification code to the user.

**Comment by Juan-Olivos** [comment]
Fixed the Duo login issue by displaying the code as suggested. Thanks for your help.
